# Generated by Django 5.0.1 on 2024-02-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tasks",
            field=models.ManyToManyField(to="users.user"),
        ),
    ]
