# Generated by Django 5.0.1 on 2024-02-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("done", "DONE"),
                    ("processing", "PROCESSING"),
                    ("no work", "NO WORK"),
                ],
                default=("no work", "NO WORK"),
                max_length=63,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
