# Generated by Django 5.0.1 on 2024-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_task_status_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tasks",
            field=models.ManyToManyField(to="users.task"),
        ),
    ]
